# Generated by Django 2.2.12 on 2020-10-04 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='user',
        ),
        migrations.RemoveField(
            model_name='token',
            name='user',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.DeleteModel(
            name='Income',
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
